jobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import *

app_name = "jobs"
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('create-job/', CreateJobView.as_view(), name="create_job"),
    path('search/', SearchJobView.as_view(), name="search"),
    path('detail/<slug>/<int:pk>/', SingleJobView.as_view(), name="single_job"),
    path('update/<slug>/<int:pk>/', UpdateJobView.as_view(), name="update_job"),
    path('delete/<slug>/<int:pk>/', DeleteJobView.as_view(), name="delete_job"),
    path('category-detail/<slug>/<int:pk>/', CategoryDetailView.as_view(), name="category_detail"),
]

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as authViews

app_name = "users"
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password-change/', authViews.PasswordChangeView.as_view(), name='password_change'),
    path('password-change-done/', authViews.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('update-profile/<int:pk>/', UserUpdateView.as_view(), name='update_profile'),
    path('employee-profile/<int:employee_id>/<int:job_id>/', EmployeeProfileView.as_view(), name='employee_profile'),
    path('employer-jobs/', EmployerPostedJobsView.as_view(), name='employer_jobs'),
    path('employee-jobs/', EmployeeAppliedJobsView.as_view(), name='employee_jobs'),
    path('employee-messages/<int:pk>/', EmployeeMessagesView.as_view(), name='employer_messages'),
    path('employee-display-messages/<int:pk>/', EmployeeDisplayMessages.as_view(), name='employer_display_messages'),
    path('add-wishlist/<int:pk>/', AddWishListView.as_view(), name='add_wishlist'),
    path('remove-from-wishlist/<int:pk>/', RemoveFromWishListView.as_view(), name='remove_from_wishlist'),
    path('mywishlist/<int:pk>/', MyWishList.as_view(), name='my_wish_list'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Job Portal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">

    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">


    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

  </head>
  <body>

	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'jobs:home' %}">EDF Energy</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="{% url 'jobs:home' %}" class="nav-link">Home</a></li>
                {% if not user.is_authenticated %}
                  <li class="nav-item cta mr-md-2"><a href="{% url 'users:register' %}" class="nav-link">Register</a></li>
                  <li class="nav-item cta cta-colored"><a href="{% url 'users:login' %}" class="nav-link">Login</a></li>
                {% endif %}
                {% if user.is_authenticated and user.is_employee %}
                    <div class="btn-group">
                      <button type="button" class="btn btn-success dropdown-toggle" style="height:50px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                              {{ user.first_name }}
                      </button>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'users:employee_jobs' %}">My jobs</a>
                        <a class="dropdown-item" href="{% url 'users:employer_messages' pk=user.pk %}">You have {{ user.count_unread_messages }} message(s)</a>
                        <a class="dropdown-item" href="{% url 'users:my_wish_list' pk=user.id %}">My wish list</a>
                        <a class="dropdown-item" href="{% url 'users:update_profile' pk=user.get_profile_id %}">Update profile</a>
                        <a class="dropdown-item" href="{% url 'users:password_change' %}">Change password</a>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                      </div>
                    </div>
                {% endif %}
                {% if user.is_authenticated and user.is_employer %}
                    <div class="btn-group">
                      <button type="button" class="btn btn-success dropdown-toggle" style="height:50px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          {{ user.first_name }}
                      </button>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'jobs:create_job' %}">Add job</a>
                        <a class="dropdown-item" href="{% url 'users:employer_jobs' %}">My jobs</a>
                        {% if user.get_profile_id %}
                            <a class="dropdown-item" href="{% url 'users:update_profile' pk=user.get_profile_id %}">Update profile</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'users:password_change' %}">Change password</a>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                      </div>
                    </div>
                {% endif %}
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
{% block content %}

  {% endblock %}

    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
        	<div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About</h2>
              <p>EDF Energy is a British integrated energy company with operations spanning electricity generation and the sale of natural gas and electricity to homes and businesses throughout the United Kingdom.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                <li class="ftco-animate"><a href="https://twitter.com/edfenergy"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="https://www.facebook.com/edfenergy"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="https://www.instagram.com/edfenergy/"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>

          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, London, United Kingdom</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@fakeedfenergy.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
  <script src="{% static "js/jquery.timepicker.min.js" %}"></script>
  <script src="{% static "js/scrollax.min.js" %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static "js/google-map.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>
  {% if user.is_authenticated and user.is_employee %}
      <script src="{% static "js/addorremove.js" %}"></script>
  {% else %}
      <script src="{% static "js/addorremovenotauth.js" %}"></script>
  {% endif %}

  </body>
</html>